s(:begin,
  s(:send, nil, :require,
    s(:str, "test/unit")),
  s(:module,
    s(:const, nil, :Bug),
    s(:begin,
      s(:class,
        s(:const, nil, :Bug7802),
        s(:const, nil, :RuntimeError), nil),
      s(:class,
        s(:const, nil, :TestException),
        s(:const,
          s(:const,
            s(:const, nil, :Test), :Unit), :TestCase),
        s(:def, :test_ensured,
          s(:args),
          s(:send, nil, :assert_separately,
            s(:array),
            s(:dstr,
              s(:str, "\n"),
              s(:str, "        require '-test-/exception'\n"),
              s(:str, "\n"),
              s(:str, "        module Bug\n"),
              s(:str, "          class Bug7802 < RuntimeError\n"),
              s(:str, "            def try_method\n"),
              s(:str, "              raise self\n"),
              s(:str, "            end\n"),
              s(:str, "\n"),
              s(:str, "            def ensured_method\n"),
              s(:str, "              [1].detect {|i| true}\n"),
              s(:str, "            end\n"),
              s(:str, "          end\n"),
              s(:str, "        end\n"),
              s(:str, "\n"),
              s(:str, "        assert_raise(Bug::Bug7802, '[ruby-core:52022] [Bug #7802]') {\n"),
              s(:str, "          Bug::Exception.ensured(Bug::Bug7802.new)\n"),
              s(:str, "        }\n"))))))))
